-- Migration: Create temp_artifact_metadata table
-- This table stores all parsed LLM metadata in a wide format for review/analysis

CREATE TABLE IF NOT EXISTS temp_artifact_metadata (
	id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	image_id TEXT,
	subject TEXT,
	dealer_name TEXT,
	suspected_current_location TEXT,
	artifact_title TEXT,
	photograph_location TEXT,
	first_appearance_year INTEGER,
	first_appearance_year_outside_cambodia INTEGER,
	repatriated BOOLEAN DEFAULT FALSE,
	image_source TEXT,
	material TEXT,
	has_inscription BOOLEAN DEFAULT FALSE,
	multiple_heads BOOLEAN DEFAULT FALSE,
	four_arms BOOLEAN DEFAULT FALSE,
	eight_arms BOOLEAN DEFAULT FALSE,
	ten_arms BOOLEAN DEFAULT FALSE,
	over_ten_arms BOOLEAN DEFAULT FALSE,
	fragmentary BOOLEAN DEFAULT FALSE,
	fragments_from_multiple_statues BOOLEAN DEFAULT FALSE,
	head_present BOOLEAN DEFAULT FALSE,
	torso_present BOOLEAN DEFAULT FALSE,
	shoulder_elbow_present BOOLEAN DEFAULT FALSE,
	elbow_wrist_present BOOLEAN DEFAULT FALSE,
	hip_knee_present BOOLEAN DEFAULT FALSE,
	knee_ankle_present BOOLEAN DEFAULT FALSE,
	foot_present BOOLEAN DEFAULT FALSE,
	base_present BOOLEAN DEFAULT FALSE,
	fragmented_at_neck BOOLEAN DEFAULT FALSE,
	fragmented_at_shoulder BOOLEAN DEFAULT FALSE,
	fragmented_at_elbow BOOLEAN DEFAULT FALSE,
	fragmented_at_wrist BOOLEAN DEFAULT FALSE,
	fragmented_at_upper_leg BOOLEAN DEFAULT FALSE,
	fragmented_at_knee BOOLEAN DEFAULT FALSE,
	fragmented_at_ankle BOOLEAN DEFAULT FALSE,
	created_at TIMESTAMP DEFAULT NOW()
);
